// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type ArticleDailyArgs = {
  "domain": string;
};

export type ArticleDailyReturns = {
  "key": {
    "day": string;
  };
  "grouping": string[];
  "elements": {
    "id": string;
  }[];
}[];

export async function articleDaily(client: Executor, args: ArticleDailyArgs): Promise<ArticleDailyReturns> {
  return client.query(`\
with M:= (select Article {*} filter .website.domain like <str>$domain)
group M
using day := to_str(.a_published_at)[0:10]
by day`, args);

}
