# AUTOGENERATED FROM 'webapp/src/routes/getDomains.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class getDomainsResult(NoPydanticValidation):
    id: uuid.UUID
    domain: str


async def getDomains(
    executor: edgedb.AsyncIOExecutor,
) -> list[getDomainsResult]:
    return await executor.query(
        """\
        select Website {domain};\
        """,
    )
