// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type GetDomainsReturns = {
  "domain": string;
}[];

export async function getDomains(client: Executor): Promise<GetDomainsReturns> {
  return client.query(`\
select Website {domain};`);

}
