// GENERATED by @edgedb/generate v0.3.3

import type {Executor} from "edgedb";

export type Search_embeddingArgs = {
  "description_embedding": Float32Array;
};

export type Search_embeddingReturns = {
  "title": string | null;
  "description": string | null;
  "url": string;
}[];

export async function search_embedding(client: Executor, args: Search_embeddingArgs): Promise<Search_embeddingReturns> {
  return client.query(`\
select Article {title, description, url:=.webpage.website.domain ++ .webpage.path}
order by ext::pgvector::euclidean_distance(
  .description_embedding, <BertEmbedding>$description_embedding)
empty last
limit 10;`, args);

}
