# AUTOGENERATED FROM 'postprocessor/src/queries/get_unprocessed_webpages.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUnprocessedWebpagesResult(NoPydanticValidation):
    path: str
    created_at: datetime.datetime
    id: uuid.UUID
    modified_at: datetime.datetime
    lastmod: datetime.datetime
    html: str


async def get_unprocessed_webpages(
    executor: edgedb.AsyncIOExecutor,
    *,
    domain: str,
) -> list[GetUnprocessedWebpagesResult]:
    return await executor.query(
        """\
        select Webpage {*} filter {
            not exists .article AND
            .website.domain =<str>$domain
        };\
        """,
        domain=domain,
    )
