# AUTOGENERATED FROM 'postprocessor/src/queries/get_articles_without_title_embeddings.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import array
import dataclasses
import datetime
import edgedb
import uuid


BertEmbedding = array.array


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetArticlesWithoutTitleEmbeddingsResult(NoPydanticValidation):
    modified_at: datetime.datetime
    created_at: datetime.datetime
    id: uuid.UUID
    a_published_at: datetime.datetime | None
    a_modified_at: datetime.datetime | None
    authors: list[str] | None
    content_text: str | None
    description: str | None
    section: str | None
    tags: list[str] | None
    title: str | None
    description_embedding: BertEmbedding | None
    title_embedding: BertEmbedding | None


async def get_articles_without_title_embeddings(
    executor: edgedb.AsyncIOExecutor,
    *,
    domain: str,
) -> list[GetArticlesWithoutTitleEmbeddingsResult]:
    return await executor.query(
        """\
        select Article {*} filter  {
            .title_embedding = <BertEmbedding>array_fill(0,1024) AND
            .website.domain = <str>$domain
        };\
        """,
        domain=domain,
    )
