# AUTOGENERATED FROM 'postprocessor/src/queries/update_article_title_embedding.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import typing
import uuid


TitleEmbedding = typing.Sequence[float]


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateArticleTitleEmbeddingResult(NoPydanticValidation):
    id: uuid.UUID


async def update_article_title_embedding(
    executor: edgedb.AsyncIOExecutor,
    *,
    uuid: uuid.UUID,
    title_embedding: TitleEmbedding,
) -> UpdateArticleTitleEmbeddingResult | None:
    return await executor.query_single(
        """\
        update Article
        filter .id = <uuid>$uuid
        set {
            title_embedding := <BertEmbedding>$title_embedding
        };\
        """,
        uuid=uuid,
        title_embedding=title_embedding,
    )
